version: '3'
services:
  consumer:
    image: pcrofts/tmkafka
    command: consume --debug
    links:
      - counter
      - kafka
  counter:
    image: pcrofts/tmcounter
  kafka:
    image: spotify/kafka
    ports:
    - "9092:9092"
    - "2181:2181"
volumes:
  logvolume01: {}