logging:
  level: INFO
kafka:
  broker: 10.40.184.70:9092
  partitions: all
  topic: tmgo
  group: tmgo1
  initialOffset: oldest # or newest
  message: '{"name":"Paul"}'
  consumer:
    bufferSize: 128
counter:
  address: 10.40.184.70:8079